# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  timeFormat: "06-01-02"
  shortTimeFormat: "15:04"

  theme:
    nerdFontsVersion: "3"

  showCommandLog: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

update:
  method: never

promptToReturnFromSubprocess: false

