# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on   = ["g", "w"]
run  = "cd /w"
desc = "Go /w"

[[mgr.prepend_keymap]]
on   = ["g", "d"]
run  = "cd ~/Documents"
desc = "Go ~/Documents"

[[mgr.prepend_keymap]]
on   = ["g", "c"]
run  = "cd ~/.config"
desc = "Go ~/.config"

[[mgr.prepend_keymap]]
on   = ["g", "l", "s"]
run  = "cd ~/.local/share"
desc = "Go local share"

[[mgr.prepend_keymap]]
on   = ["g", "l", "b"]
run  = "cd ~/.local/bin"
desc = "Go local bin"

[[mgr.prepend_keymap]]
on   = ["g", "l", "t"]
run  = "cd ~/.local/state"
desc = "Go local state"

[[mgr.prepend_keymap]]
on   = "d"
run  = "remove --permanently"
desc = "Permanently delete selected files"

[[mgr.prepend_keymap]]
on   = ";"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = "shell --interactive"
desc = "Run a shell command"

[[mgr.prepend_keymap]]
on = [ "l" ]
run = "plugin bypass smart-enter"
desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory"

[[mgr.prepend_keymap]]
on = [ "h" ]
run = "plugin bypass reverse"
desc = "Recursively enter parent directory, skipping parents with only a single subdirectory"

[[mgr.prepend_keymap]]
on = [ "<C-h>" ]
run = "leave"
desc = "Back to the parent directory"

[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on  = "<A-d>"
run = 'shell -- dragon-drop -x -T "$@"'

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on  = "q"
run = "plugin confirm-quit -- --no-cwd-file"
desc = "Quit without outputting cwd-file"

[[mgr.prepend_keymap]]
on  = "Q"
run = "plugin confirm-quit"
desc = "Quit the process"

[[mgr.prepend_keymap]]
on   = "i"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on   = "\\"
run  = "filter --smart"
desc = "Filter files"

[[mgr.prepend_keymap]]
on   = [ "1" ]
run  = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "2" ]
run  = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "3" ]
run  = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "4" ]
run  = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "5" ]
run  = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "6" ]
run  = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "7" ]
run  = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "8" ]
run  = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = [ "9" ]
run  = "plugin relative-motions 9"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "<A-1>"
run  = "tab_switch 0"
desc = "Switch to first tab"

[[mgr.prepend_keymap]]
on   = "<A-2>"
run  = "tab_switch 1"
desc = "Switch to second tab"

[[mgr.prepend_keymap]]
on   = "<A-3>"
run  = "tab_switch 2"
desc = "Switch to third tab"

[[mgr.prepend_keymap]]
on   = "<A-4>"
run  = "tab_switch 3"
desc = "Switch to fourth tab"

[[mgr.prepend_keymap]]
on   = "<A-5>"
run  = "tab_switch 4"
desc = "Switch to fifth tab"

[[mgr.prepend_keymap]]
on   = "<A-6>"
run  = "tab_switch 5"
desc = "Switch to sixth tab"

[[mgr.prepend_keymap]]
on   = "<A-7>"
run  = "tab_switch 6"
desc = "Switch to seventh tab"

[[mgr.prepend_keymap]]
on   = "<A-8>"
run  = "tab_switch 7"
desc = "Switch to eighth tab"

[[mgr.prepend_keymap]]
on   = "<A-9>"
run  = "tab_switch 8"
desc = "Switch to ninth tab"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = [ "g", "C" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

[[mgr.prepend_keymap]]
on   = "<A-y>"
run  = "plugin copy-file-contents"
desc = "Copy contents of file"

# or this if you want to jump to mountpoint after mounted
[[mgr.prepend_keymap]]
on   = [ "M", "m" ]
run  = "plugin gvfs -- select-then-mount --jump"
desc = "Select device to mount and jump to its mount point"

# This will remount device under cwd (e.g. cwd = /run/user/1000/gvfs/DEVICE_1/FOLDER_A, device mountpoint = /run/user/1000/gvfs/DEVICE_1)
[[mgr.prepend_keymap]]
on   = [ "M", "R" ]
run  = "plugin gvfs -- remount-current-cwd-device"
desc = "Remount device under cwd"

[[mgr.prepend_keymap]]
on   = [ "M", "u" ]
run  = "plugin gvfs -- select-then-unmount"
desc = "Select device then unmount"

# Add|Edit|Remove mountpoint: smb, sftp, ftp, nfs, google-drive, dns-sd, dav, davs, dav+sd, davs+sd, afp, afc, sshfs
# Read more about the schemes here: https://wiki.gnome.org/Projects(2f)gvfs(2f)schemes.html
# For example: smb://user:password@192.168.1.2/share, sftp://user@192.168.1.2/, ftp://192.168.1.2/
[[mgr.prepend_keymap]]
on   = [ "M", "a" ]
run  = "plugin gvfs -- add-mount"
desc = "Add a GVFS mount URI"

[[mgr.prepend_keymap]]
on   = [ "M", "e" ]
run  = "plugin gvfs -- edit-mount"
desc = "Edit a GVFS mount URI"

[[mgr.prepend_keymap]]
on   = [ "M", "r" ]
run  = "plugin gvfs -- remove-mount"
desc = "Remove a GVFS mount URI"

# Jump
[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "plugin gvfs -- jump-to-device"
desc = "Select device then jump to its mount point"

[[mgr.prepend_keymap]]
on   = [ "`", "`" ]
run  = "plugin gvfs -- jump-back-prev-cwd"
desc = "Jump back to the position before jumped to device"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"
